### ISSUE TITLE
AU cannot play a specific software artwork

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2855]
It just show a black screen when play in artwork in artwork detail screen. Please use this token to debug. 
eth-0x28b51BA8B990c48CB22cB6EF0ad5415fdBA5210C-101203243301117787559401599223798510155457323902733064063026283969832858934912

**Comment by ppupha** [comment]
preveiUrl: https://ddsm7s9hd8znk.cloudfront.net/previews/9983bf66-380e-4af3-bee9-237c492f18a0/1615757415/index.html

texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?

**Comment by ppupha** [comment]
This bug is fixed together with [The "Filum" artwork in Truth show cannot play in AU application](https://github.com/bitmark-inc/autonomy-apps/issues/3088)

**Comment by longbmk** [comment]
@ppupha This bug still happens when it can't play in the artwork preview screen. Moreover, in iPhone, it does not show correct center of artwork.
![IMG_490DCBA997F3-1](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/ec45f62e-5c25-45c6-a2a6-a5b26b578d1a)

**Comment by ppupha** [comment]
This issue is similar to [Artworks in GRAPH+ show is zoom in when playing in Autonomy](https://github.com/bitmark-inc/autonomy-apps/issues/3187)

**Comment by longbmk** [comment]
This issue still happens in Preview screen.

**Comment by anhnguyenbitmark** [comment]
To test in a more powerful device to confirm if this is a performance issue. If yes, we don't need to fix.

**Comment by longbmk** [comment]
This artwork still cannot play in iPhone 13 promax. Let's fix it @ppupha

**Comment by ppupha** [comment]
[Note]
Safari on iphone Xs max can not play previewUrl.

**Comment by nunguyen3101** [comment]
Track it on ticket https://github.com/bitmark-inc/feralfile-app/issues/2195
