### ISSUE TITLE
MoMA Postcard / Remove Feral File and MoMA logo from web3 glossary.

### ISSUE THREAD

**Issue by bencebitmark** [bitmark-inc/autonomy-apps#2937]
[Design](https://www.figma.com/file/pEiCw9VDBkDv4OJzhnb3wB/Autonomy-%232937-%2F-MoMA-Postcard-%2F-Updates-to-web3-glossary?type=design&node-id=0%3A1&mode=design&t=I5nC0jKte7FSkLpC-1).

**Comment by ppupha** [comment]
@bencebitmark Do you know who from production team can work on it?

**Comment by bencebitmark** [comment]
@ppupha i'll update the pdf tomorrow. not sure who from engineering can replace it.

**Comment by bencebitmark** [comment]
@anhnguyenbitmark @ppupha design is ready.

**Comment by ppupha** [comment]
@anhnguyenbitmark can this bugs be fixed together with [autonomy.io website](https://github.com/bitmark-inc/autonomy/issues/2141)

**Comment by anhnguyenbitmark** [comment]
No, but it's not from the mobile side either. @ppupha let me just remove you and fix the assignment.

**Comment by bm-kiennguyen** [comment]
Client tasks - 0.5 units
- Remove Autonomy Logo
- Update background for each page
- Change text on `Web3 Wallet, Generative Art, On–chain Art`
- Update style for first page

**Comment by bencebitmark** [comment]
@anhnguyenbitmark what's the status of this?

**Comment by longbmk** [comment]
@bencebitmark This is deployed.

**Comment by bencebitmark** [comment]
@longbmk is it on prod release?

**Comment by ppupha** [comment]
@bencebitmark i see it was deployed to prd.

**Comment by bencebitmark** [comment]
@ppupha @longbmk i still see the old version – does it apply only to newly minted postcards?

**Comment by ppupha** [comment]
@bencebitmark Au app play an inappwebview, so. when the site is deployed,  it should be apply for all

https://github.com/bitmark-inc/autonomy-apps/assets/47568867/bd39afd7-9fd8-4bcd-9c97-f764e0e03aa1

**Comment by bencebitmark** [comment]
strange, not updated for me.

**Comment by ppupha** [comment]
@bencebitmark there was an issue and it not happened on all devices. We fixed it and waiting for deployment.

**Comment by ppupha** [comment]
@bencebitmark we deployed new fix, please help to check if the issue is fixed.

**Comment by bencebitmark** [comment]
@ppupha still not showing me the new one.


https://github.com/bitmark-inc/autonomy-apps/assets/128143921/452eac01-a6db-42dd-a53f-bb3161817855
