### ISSUE TITLE
Freeze app when opening the app

### ISSUE THREAD

**Issue by thuyenBitmark** [bitmark-inc/autonomy-apps#76]
|<img src="https://user-images.githubusercontent.com/50816149/171775493-ea7f5619-f8cb-4a43-9941-3befe40ac0c1.jpg" width=350/> |<img src="https://user-images.githubusercontent.com/50816149/171775479-860c7dba-ccd6-4076-9727-65fdd7d45dbf.png" width=350/> |

**Comment by NekhDRej** [comment]
The issue is fixed

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10

**Comment by longbmk** [comment]
Sometimes, this issue still happens. We need to investigate more about it.

**Comment by hungqd** [comment]
Can't reproduce on:
- Mi 10T lite - android 12
- iPhone 8 - iOS 15.6

**Comment by longbmk** [comment]
https://github.com/bitmark-inc/au-support-board-test/issues/825

This is the newest logs we got at the first time we open the app after installing

**Comment by hungqd** [comment]
@longbmk log file is from old version of the app. I can't reproduce on latest version. Could you please help verify this on the latest one. Thank you.
